@hostname = http://localhost
@port = 3004
@host = {{hostname}}:{{port}}

###
GET {{host}}/events

### 
GET {{host}}/tags?id=0&id=1

###
POST {{host}}/events
Content-Type: application/json

{
	"date": "2021-07-01",
	"placeID": 0,
	"tags": [0, 1	],
	"event_type": [0],
	"title": "Просто какое-то событие",
	"description": "Невероятное культурное событие",
	"image": "unblivible.jpg",
	"price_from": 1500
}